const CREATE_CALENDAR_POPUP_DISABLE_KEY = 'CREATE_CALENDAR_POPUP_DISABLE';
const CREATE_MEETING_NOTI_DISABLE_KEY = 'CREATE_MEETING_NOTI_DISABLE';
const TUTORIAL_DISABLE_KEY = 'TUTORIAL_DISABLE';

export {
  CREATE_CALENDAR_POPUP_DISABLE_KEY,
  CREATE_MEETING_NOTI_DISABLE_KEY,
  TUTORIAL_DISABLE_KEY,
};
