/*
 * 제목 15자
 * 상세정보 100자
 * 온라인 100자
 * 오프라인 30자
 * 참조 링크 100자
 * */
const MAX_TITLE_LENGTH = 15;
const MAX_TITLE_LENGTH_ERROR = `글자수가 ${MAX_TITLE_LENGTH}자를 넘었어요.`;

const MAX_DESCRIPTION_LENGTH = 100;
const MAX_DESCRIPTION_LENGTH_ERROR = `글자수가 ${MAX_DESCRIPTION_LENGTH}자를 넘었어요.`;

const MAX_ATTACHMENT_LENGTH = 300;
const MAX_ATTACHMENT_LENGTH_ERROR = `글자수가 ${MAX_ATTACHMENT_LENGTH}자를 넘었어요.`;

const MAX_ONLINE_LOCATION_LENGTH = 300;
const MAX_ONLINE_LOCATION_LENGTH_ERROR = `글자수가 ${MAX_ONLINE_LOCATION_LENGTH}자를 넘었어요.`;

const MAX_OFFLINE_LOCATION_LENGTH = 30;
const MAX_OFFLINE_LOCATION_LENGTH_ERROR = `글자수가 ${MAX_OFFLINE_LOCATION_LENGTH}자를 넘었어요.`;

const INVALID_URL_ERROR = 'http(s):// 로 시작해야 해요.';

const MAX_DECLINE_REASON_LENGTH = 100;
const MAX_DECLINE_REASON_LENGTH_ERROR = `글자수가 ${MAX_DECLINE_REASON_LENGTH}자를 넘었어요.`;

const MAX_NAME_LENGTH = 20;
const MAX_NAME_LENGTH_ERROR = `글자수가 ${MAX_NAME_LENGTH}자를 넘었어요.`;

const INVALID_EMAIL_ERROR = '올바른 이메일 형식이 아니에요.';

const REQUIRED_ERROR = '필수 입력사항입니다.';

export {
  MAX_TITLE_LENGTH,
  MAX_DESCRIPTION_LENGTH,
  MAX_ATTACHMENT_LENGTH,
  MAX_ONLINE_LOCATION_LENGTH,
  MAX_OFFLINE_LOCATION_LENGTH,
  MAX_TITLE_LENGTH_ERROR,
  MAX_DESCRIPTION_LENGTH_ERROR,
  MAX_ATTACHMENT_LENGTH_ERROR,
  MAX_ONLINE_LOCATION_LENGTH_ERROR,
  MAX_OFFLINE_LOCATION_LENGTH_ERROR,
  INVALID_URL_ERROR,
  MAX_DECLINE_REASON_LENGTH,
  MAX_DECLINE_REASON_LENGTH_ERROR,
  MAX_NAME_LENGTH,
  MAX_NAME_LENGTH_ERROR,
  INVALID_EMAIL_ERROR,
  REQUIRED_ERROR,
};
